POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMjMiLCJpZCI6IjY0ZmE0NDViMjdkMzZhMDQ0NTRiMmQ2ZiIsImlhdCI6MTY5NDEyNDY1Nn0.BWfVQp32cAJuWctT2z8JqiYIZOUw2j0-vIgkDlnsLJA

{
  "title": "Traveling Tips for Beginners",
  "author": "Sarah Johnson",
  "url": "https://www.example.com/traveling-tips",
  "likes": 78
}


